### PR TITLE
Improve applying the theme mode

### PR DESCRIPTION
**Pull request by ZahraHeydari**
I faced some tiny issues related to the theme mode. So I fixed them.

- Now there is no blink while switching between the theme modes.
- The icon of each mode is displayed based on its action.
- The color of the status bar is changed while applying the light or dark mode.

### CODE REVIEW

**Review by Drjacky — CHANGES_REQUESTED** [review]
Thank you for your participation.
- In the light theme, icons on the status bar are not visible as they are white too:
Screenshot 2023-02-09 at 22 08 53

**Review by Drjacky — CHANGES_REQUESTED** [review]
Screenshot 2023-02-11 at 09 45 04

**Review by Drjacky — CHANGES_REQUESTED** [review]
Sorry but on API 21:
Screenshot 2023-02-11 at 14 47 49

**Comment by ZahraHeydari** [comment]
> Sorry but on API 21:
> Screenshot 2023-02-11 at 14 47 49

Although, I'm not sure that it's a good idea to remove setting the status bar color for Android API 21 to 23 due to not supporting it, I removed it anyway.

**Pull request merged**
